In [38]:
import numpy as np
v1=np.array([1,-1,1,-1])
v2=np.array([-1,1,-1,1])
v3=np.array([1,1,-1,-1])
v4=np.array([-1,-1,1,1])

vectors=[v1,v2,v3,v4]



In [39]:
#initialize the weight matrix
n=len(v1)
w=np.zeros((n,n))
w

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
#training weight updation using the hebbian rule
for v in vectors:
    w+=np.outer(v,v)

np.fill_diagonal(w,0) #self connection of the neuron was removed.
print(f"final weight matrix is:{w}")

final weight matrix is:[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]


In [53]:
#testing
test_vector=np.array([1,-1,1,-1])
print(f"test vector:{test_vector}")

test vector:[ 1 -1  1 -1]


In [54]:
def sign(x):
    return np.where(x>=0,1,-1)

result=np.dot(w,test_vector)
recalled_pattern=sign(result)
    
print(f"recalled_pattern:{recalled_pattern}")

recalled_pattern:[ 1 -1  1 -1]


In [ ]:
#hopfield network sometimes generate the spurious state which is the false stable state because of the lots of vectors (patterns) are stored in the weight matrix.